server {
    listen 80;

    location = /manifest.webmanifest {
        root /usr/share/nginx/html;
        default_type application/json;
        add_header Access-Control-Allow-Origin "*";
    }

    location / {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin "*";
    }
}
